local M = {}
local utils = require"faust-nvim/utils"

-- Updated  02-02-2022
local faust2appletcommands = {
	"faust2alqt",
	"faust2alsa",
	"faust2alsaconsole",
	"faust2android",
	"faust2androidunity",
	"faust2api",
	"faust2atomsnippets",
	"faust2au",
	"faust2audiokit",
	"faust2bela",
	"faust2cagtk",
	"faust2caqt",
	"faust2caqtios",
	"faust2cpalrust",
	"faust2csound",
	"faust2csvplot",
	"faust2daisy",
	"faust2dplug",
	"faust2dssi",
	"faust2dummy",
	"faust2dummymem",
	"faust2eps",
	"faust2esp32",
	"faust2faustvst",
	"faust2feh",
	"faust2firefox",
	"faust2gen",
	"faust2graph",
	"faust2graphviewer",
	"faust2ios",
	"faust2jack",
	"faust2jackconsole",
	"faust2jackrust",
	"faust2jackserver",
	"faust2jaqt",
	"faust2jaqtchain",
	"faust2juce",
	"faust2ladspa",
	"faust2linuxunity",
	"faust2lv2",
	"faust2mathdoc",
	"faust2mathviewer",
	"faust2max6",
	"faust2md",
	"faust2minimal",
	"faust2msp",
	"faust2netjackconsole",
	"faust2netjackqt",
	"faust2nodejs",
	"faust2octave",
	"faust2osxiosunity",
	"faust2owl",
	"faust2paqt",
	"faust2pdf",
	"faust2plot",
	"faust2png",
	"faust2portaudiojulia",
	"faust2portaudiorust",
	"faust2pure",
	"faust2puredata",
	"faust2raqt",
	"faust2ros",
	"faust2rosgtk",
	"faust2rpialsaconsole",
	"faust2rpinetjackconsole",
	"faust2sam",
	"faust2sc",
	"faust2sc.py",
	"faust2sig",
	"faust2sigviewer",
	"faust2smartkeyb",
	"faust2sndfile",
	"faust2soul",
	"faust2sublimecompletions",
	"faust2supercollider",
	"faust2svg",
	"faust2svgviewer",
	"faust2teensy",
	"faust2unity",
	"faust2vcvrack",
	"faust2vst",
	"faust2vsti",
	"faust2w32max6",
	"faust2w32msp",
	"faust2w32puredata",
	"faust2w32vst",
	"faust2w64max6",
	"faust2w64puredata",
	"faust2w64vst",
	"faust2wasm",
	"faust2webaudiowasm",
	"faust2webaudiowast",
	"faust2winunity",
}

for _,faust2command in ipairs(faust2appletcommands) do
	local command_name = faust2command:gsub("faust2", "") -- Remove the faust2 part
	M[command_name] = function (arguments)
		local file = vim.fn.expand("%")
		local cmd = string.format(faust2command .. " %s", file)
		utils.make(cmd,arguments)
	end
end

return M
